### ISSUE TITLE
Running with sketch files as input

### ISSUE THREAD

**Issue by andrewsanchez** [lskatz/mashtree#10]
Is it possible to use those as input instead of the FASTAs?

How much work would it be to implement this feature in mashtree?

**Comment by lskatz** [comment]
That sounds possible.

**Comment by lskatz** [comment]
Added in e426b4e068793fef6583a22b0402be5ddfe7021e

I'll make a version 0.21 at a later time

**Comment by lskatz** [comment]
Never mind, I went ahead and made v0.21
