### ISSUE TITLE
SQLite error: too many terms in compound SELECT

### ISSUE THREAD

**Issue by rrwick** [lskatz/mashtree#11]
Not an active issue - I've got it working. Just thought I'd post it here for future reference!

I was running Mashtree with a lot of bacterial genomes (about 400) and DBD::SQLite was crashing with a 'too many terms in compound SELECT' error. I found that SQLite has a limit on the number of terms in a compound select statement which is set at compile time using the `SQLITE_MAX_COMPOUND_SELECT` parameter.

I got around the problem by compiling the DBD::SQLite module with an increased value for that parameter:
```sh
wget http://search.cpan.org/CPAN/authors/id/I/IS/ISHIGAKI/DBD-SQLite-1.54.tar.gz
tar -xf DBD-SQLite-1.54.tar.gz
cd DBD-SQLite-1.54
sed -i 's|SQLITE_MAX_COMPOUND_SELECT 500|SQLITE_MAX_COMPOUND_SELECT 1000000|g' sqlite3.c
perl Makefile.PL INSTALL_BASE=$HOME/.local/perl
make
make install
```

I'm not sure how high I needed to make it, but 1000000 worked fine.

Then I needed to make sure Perl was using this version of the module:
```
export PERL5LIB=$HOME/.local/perl/lib/perl5:$HOME/.local/perl/lib/perl5/x86_64-linux-thread-multi:$PERL5LIB
```

And then Mashtree happily worked for all 400 genomes!

**Comment by lskatz** [comment]
How bizarre!  I didn't know that there was maximum for the select statement.  I'll reopen this issue so that I chunk the select statements at a later time.

**Comment by lskatz** [comment]
I tried to repeat this error with 5001 fastq files.  The 5001 each have the same content.  Despite this trial, I was not able to repeat the error.  If you have a dataset, I will try to repeat it with that dataset; otherwise I will re-close this issue.

**Comment by rrwick** [comment]
I have a dataset of 372 _Klebsiella_ genomes which causes the issue on my system. I'm happy to share it, but it's about 600 MB when zipped up. How should I get it to you? Dropbox?

Here are some details:


### Info

Distro: Red Hat Enterprise Linux Server release 6.9 (Santiago)
Software versions: Mashtree v0.22, Mash v1.1.1, BioPerl v1.6.924
Command:
```
mashtree.pl --genomesize 5500000 --sketch-size 100000 --numcpus 16 klebsiella_all/*.fasta > mashtree.dnd
```

### Failed run

This run used the DBD-SQLite that was installed on my system. It is v1.42 and presumably used the default of 500 for `SQLITE_MAX_COMPOUND_SELECT`.

[failed_run_output.txt](https://github.com/lskatz/mashtree/files/1357818/failed_run_output.txt)

### Successful run

This run used my custom version of DBD-SQLite. It is v1.54 and I set `SQLITE_MAX_COMPOUND_SELECT` to 1000000 when compiling.

[successful_run_output.txt](https://github.com/lskatz/mashtree/files/1357830/successful_run_output.txt)
[successful_run_tree.dnd.txt](https://github.com/lskatz/mashtree/files/1357831/successful_run_tree.dnd.txt)


Let me know how I can get the genomes to you and if there's anything else you need!

**Comment by lskatz** [comment]
Do you have assembly or nuccore accessions?

**Comment by rrwick** [comment]
Sure, here are the accessions: [accessions.txt](https://github.com/lskatz/mashtree/files/1361059/accessions.txt)
And here are commands which I think will download them: [download_commands.txt](https://github.com/lskatz/mashtree/files/1361060/download_commands.txt)

Ryan

**Comment by lskatz** [comment]
Thanks!  I'm downloading now but will have to test this over time.  The download commands are super helpful, thanks

**Comment by lskatz** [comment]
I think I fixed this issue by chunking insert statements into 99 or fewer.  Originally, the insert statements all happened in a single SQL query.  This is reflected in v0.25 and was fixed in 318e87f0c7f9bd27d55894f585340e34f2428658.

**Comment by lskatz** [comment]
And thank you for working on this with me and bringing it to my attention.

**Comment by rrwick** [comment]
That's great - thanks!
