### ISSUE TITLE
0.21 version not in CPAN

### ISSUE THREAD

**Issue by tseemann** [lskatz/mashtree#12]
Still downloading 0.20

**Comment by lskatz** [comment]
Good point!  Ok so the bad news is that I've been out of the office, and so I can't be certain of things.  The good news is that Travis CI tells me that v0.21 seems to be working well, and so I uploaded it to CPAN.  It should show up in a few hours.  Let me know if it works and then I'll close this issue?

**Comment by tseemann** [comment]
Installed new version via CPAN. All good!
