### ISSUE TITLE
When specificing --tempdir it doesn't delete at end

### ISSUE THREAD

**Issue by tseemann** [lskatz/mashtree#14]
Using defaults, it deletes the `tempdir` as expected as you use `tempdir(CLEANUP=>1)`

When I specificy `--tempdir ./MASHTMP` myself, it keeps all the files around after successful completion.

**Comment by lskatz** [comment]
This is as expected but I can update the usage to reflect that. The rationale is that you can reuse a tempdir to cache results for the next analysis.

**Comment by lskatz** [comment]
I totally wrote the wrong thing in the usage statement earlier and so I misled you and everyone.  It will be corrected in the next version to say that the tempdir is not deleted if specified.

**Comment by lskatz** [comment]
Fixed in 0aaac0b7464fb73c0ae14bb871d31cb9cf7017a6
