### ISSUE TITLE
No need to uncompress data for mash 

### ISSUE THREAD

**Issue by tseemann** [lskatz/mashtree#15]
Mash can read .gz files so we don't need to uncompress the files to --tempdir ?

We killed a server today when `/tmp` filled up running mashtree. Whoops :)

Is .gz support new to Mash 2.0 ?

**Comment by lskatz** [comment]
fastq.gz file can be read in Mash v1.  At least in Mash v2 (maybe in Mash v1), fasta.gz can be read also.

Fixed in 0aaac0b7464fb73c0ae14bb871d31cb9cf7017a6
