### ISSUE TITLE
Possible SQL injection attack

### ISSUE THREAD

**Issue by tseemann** [lskatz/mashtree#19]
At the moment you are manually construction SQL `INSERT` commands:
```
    $insertSQL.=qq( ("$query", "$subject", $distance), );
```

The better solution is to use SQL "prepared" statements which will do the quoting etc for you, and also simplify your code.

```
my $sth = $dbh->prepare("INSERT INTO table (genome1,genome1,distance) VALUES (?,?,?)");
foreach (entry) {
  $sth->execute($query, $subject, $distance) or die "failed to insert";
}
$sth->finish;
```

This may also help with issue #18 ?

**Comment by lskatz** [comment]
Thanks! I'll try it out!

**Comment by lskatz** [comment]
Ok so does the huge tree work with the most recent release of Mashtree?  I batched insert statements following #11 and made new releases.

**Comment by tseemann** [comment]
We were using latest mashtree.  I suspect the IDs might be really long or something? Not sure. You should still move to prepared statements.

**Comment by lskatz** [comment]
I added in `prepare` in 239f73d249c1a2b5120d0c3c589ff3b95fc94290
