### ISSUE TITLE
Consider quicktree for tree building

### ISSUE THREAD

**Issue by tseemann** [lskatz/mashtree#20]
https://github.com/khowe/quicktree

bioperl NJ gets slow for 1000s of isolates - consider this instead.

**Comment by lskatz** [comment]
added in dcaf0148103312605f374c5a50f1a6e1dc1a08dc

I made it optional such that it will be used if it is in your path.  My tests show that it is 100x faster and that it produces identical or virtually identical trees to bioperl.  Thank you for the suggestion!
