### ISSUE TITLE
0.27 failed on quicktree test

### ISSUE THREAD

**Issue by tseemann** [lskatz/mashtree#23]
```
mashtree.pl: Mashtree::createTreeFromPhylip: Creating tree with QuickTree

#   Failed test 'Mashtree produced the expected tree'
#   at t/01_filetypes.t line 20.
#          got: '(CFSAN001112.ref:0.00001,CFSAN001115.ref:0.00000,(((CFSAN001140_1:0.00019,CFSAN000968.ref:0.00001):0.00000,CFSAN000189.ref:0.00000):0.00001,((CFSAN000961.gbk:0.00005,CFSAN000211.gbk:0.00045):0.00004,(CFSAN000191.ref:0.00000,CFSAN000189.gbk:0.00000):0.00001):0.00001):0.00000);'
#     expected: '(CFSAN000189.gbk:0.00000,(CFSAN001112.ref:0.00001,CFSAN001140_1:0.00019):0.00001,((CFSAN000968.ref:0.00000,CFSAN001115.ref:0.00000):0.00001,(CFSAN000189.ref:0.00000,(CFSAN000191.ref:0.00002,(CFSAN000211.gbk:0.00045,CFSAN000961.gbk:0.00005):0.00003):0.00000):0.00001):0.00000);'
# Looks like you failed 1 test of 2.
```

```
quicktree -v
quicktree 2.2
```

**Comment by lskatz** [comment]
Should be fine in the next version.  I am basically recognizing that quicktree and bioperl make slightly different trees.  It is difficult to capture that besides just making a tree distance metric.  Which I couldn't find in any of the current required software (bioperl and maybe quicktree).  So I invented my own which measures the number of branches between every pair of leaves to their last common ancestor.  The metric is actually a Euclidean distance between the inter-leaf distances between trees.  It's probably similar to Robinson-Foulds.  The code is here if it helps make sense:

https://github.com/lskatz/mashtree/blob/master/lib/Mashtree.pm#L226

So now the unit tests make sure that the trees are somewhat related to each other and that well, there are trees that are being made.

I am going to consider whether to completely switch over to QuickTree for future versions and avoid this issue.
