### ISSUE TITLE
0.29 failed tests on cpanm install

### ISSUE THREAD

**Issue by vaofford** [lskatz/mashtree#25]
md5_hex(cat $sqliteFile) and $dbMd5sum don't seem to be equal on our setup.

cpanm Mashtree
...
sh: mashtree: command not found
01_filetypes.t: Mashtree::treeDist: Can't call method "get_nodes" on an undefined value
Stopped at lib/Mashtree.pm line 249.
\# Looks like you planned 2 tests but ran 1.
\# Looks like your test exited with 2 just after 1.
t/01_filetypes.t ..
Dubious, test returned 2 (wstat 512, 0x200)
Failed 1/2 subtests

\#   Failed test 'Added distances to the database'
\#   at t/10_sqlite.t line 44.
\# Looks like you failed 1 test of 6.
t/10_sqlite.t .....
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/6 subtests
...

**Comment by lskatz** [comment]
Hopefully fixed in #26 but I'll leave this open for now
