### ISSUE TITLE
0.29 cpanm install mashtree executable not found

### ISSUE THREAD

**Issue by vaofford** [lskatz/mashtree#26]
We've installed Mashtree via cpanm (--force as our md5 wasn't matching).

`cpanm Mashtree`

We get the depreciation warning as expected:

```
mashtree.pl -h
mashtree.pl: Mashtree::logmsg: WARNING: the executable mashtree.pl is deprecated. Please switch to the mashtree executable (without the .pl).
mashtree.pl: main::main: mashtree.pl: use distances from Mash (min-hash algorithm) to make a NJ tree
  Usage: mashtree.pl [options] *.fastq *.fasta *.gbk *.msh > tree.dnd

...

Stopped at /software/pathogen/external/lib/bin/mashtree.pl line 57.
```

But, the mashtree executable isn't copied into our bin directory, we get mashtree.pl and mashtree_wrapper.pl.  Had a hunt around the module directory, but couldn't see it there to symlink across.  

```
mashtree.pl -v
mashtree.pl: Mashtree::logmsg: WARNING: the executable mashtree.pl is deprecated. Please switch to the mashtree executable (without the .pl).
Mashtree 0.29
```

**Comment by lskatz** [comment]
I am surprised that it took this long to find this bug and that I was unaware of it!  I left it out of the manifest for the CPAN package.  To fix it short term, rename mashtree.pl to mashtree.  In the long term, I will add it into the next version.  Thank you for reporting it!
