### ISSUE TITLE
Rooted tree with BioPerl using UPGMA

### ISSUE THREAD

**Issue by mihkelvaher** [lskatz/mashtree#28]
This is more of a discussion/suggestion/pro-BioPerl argument than an issue.

Using an older version of mashtree (0.30) with BioPerl I needed a rooted tree which NJ does not produce.
That said, changing the reoccurring line
`my $dfactory = Bio::Tree::DistanceFactory->new(-method=>"NJ");`
in all files to
`my $dfactory = Bio::Tree::DistanceFactory->new(-method=>"UPGMA");`
did the trick.

Since there's no way to root with mashtree(?) maybe it's worth adding a "tree constructing algorithm" as an option?

**Comment by lskatz** [comment]
Hi, I appreciate the suggestion. However, NJ seems to yield better trees as opposed to UPGMA. I learned my session with the Lyve-SET project, that I want to leave out feature creep and so I don't see a compelling reason to add this option. However I have an open mind and am open to any rigorous comparisons you might want to share.

**Comment by mihkelvaher** [comment]
Comparing on a small E. coli set NJ gives a slightly better result than UPGMA indeed so I'm fine using NJ in general.
The question was more about rooting - UPGMA constructs a rooted tree while NJ does not (best guess rooting, as for how to root is a problem on its own).
I totally understand the feature creep problem, but I just wanted to give a hint to anyone who's facing the rooting issue since I'm using mashtree inside my own script, the rooting cannot be done manually.

**Comment by lskatz** [comment]
Gotcha! Yes rooting is a kind of issue but I don't see a clear solution. I always have to reroot for myself and don't see a great automated solution

**Comment by tseemann** [comment]
1. `nw_reroot` is in conda and brew in `newick-utils`: http://cegg.unige.ch/newick_utils
2. also consider using `mash triangle`

**Comment by mihkelvaher** [comment]
Thank you very much @lskatz and @tseemann !
nw_reroot seems to fit the task perfectly!
