### ISSUE TITLE
Bio::Tree::DistanceFactory

### ISSUE THREAD

**Issue by YaouCode** [lskatz/mashtree#3]
Hi there, 

I am using mash-Linux64-v1.1.1 and I receive the message _mashtree.pl: Bio::Tree::DistanceFactory::_nj: Can't locate object method "add_Descendents" via package "Bio::Tree::Node"_  while calling the program with 2 fasta files. I have currently perl 5, version 18, subversion 2 (v5.18.2) installed. 

Am I doing something wrong ?

Thanks

**Comment by lskatz** [comment]
I _believe_ that is because the `add_Descendents` code was added in a more recent version of BioPerl.  Could you reinstall BioPerl to the latest version and see if it fixes the problem?

**Comment by lskatz** [comment]
Actually, first try to run `make install` from the mashtree directory.  See if that installs it properly.

**Comment by YaouCode** [comment]
Hello, 
thank you for the quick response. I'm not sure I understand what you mean by running **make install** . In fact there is no makefile in the mashtree directory as far as I can tell. 
If you do not mind me asking, which version of Bioperl are you using? 
There is however no _add_Descendents_ methods in the Bio::Tree::Node package in the latest version of BioPerl. [http://search.cpan.org/dist/BioPerl/Bio/Tree/Node.pm](url) , [https://github.com/bioperl/bioperl-live/blob/master/Bio/Tree/Node.pm](url)

Thanks

**Comment by lskatz** [comment]
That's a big oversight on my part.  I uploaded the new Makefile.  Could you try it out now that it's there?

**Comment by lskatz** [comment]
I haven't heard back and so I assume everything is okay?

**Comment by lskatz** [comment]
Assuming the issue is now closed.  The issue was fixed when introducing the Makefile in 2196e94e9d80d20ca0d4cf682a9bac2e499b5c03

**Comment by mihkelvaher** [comment]
Just putting this here because the error comes up on Google:
I encountered the same error (_"add_Descendents"_). Turns out it was a typo in BioPerl:
https://github.com/bioperl/bioperl-live/issues/270
