### ISSUE TITLE
Installation issue mash tree

### ISSUE THREAD

**Issue by nidhiv132** [lskatz/mashtree#36]
I installed mash tree first with bioconda:
conda install mashtree

I did the same for mash and it worked fine. However for mashtree I get the error 
"BEGIN failed--compilation aborted at /Users/X/miniconda3/bin/mashtree line 22"

I then downloaded the package directly from GitHub and tried again, but there is no such file as Makefile.PL

Any advice?

**Comment by lskatz** [comment]
Could you post the whole log and error? I'm not sure I'm getting the whole picture yet. I'm not in control of the conda environment but if you follow the installation instructions on this site, what do you get?
