### ISSUE TITLE
Confidence values

### ISSUE THREAD

**Issue by kloetzl** [lskatz/mashtree#39]
> Mashtree can add confidence values using jack knifing.

As far as I understand the jack knifing code, it samples the hashes, which itself is already a sample of all k-mers. I think a more sound way would be to [bootstrap mash itself](https://github.com/marbl/Mash/issues/111). In the case of mashtree, just run mash multiple times with different seed values (not applicable to precomputed sketches). This then gives a new, random sample of hashes each time, a new distance matrix, and a new tree. For the latter you can then compute the consensus tree and support values.

Shouldn't be too hard to implement, except I don't know perl. :smirk:

**Comment by lskatz** [comment]
I've thought about this a few times but I held back because it might slow things down.  Thank you for writing this out.  In the future I would like to try to program it.

**Comment by kloetzl** [comment]
It will definitely slow things down. Having thought a lot about bootstrapping the past few days I am not sure anymore that my approach is ideal. But still, it might be worth investigating.

**Comment by lskatz** [comment]
Addressed in bd5a189bc8fb2b8f466a00e646568374ee9e58a0.  There is also a unit test for it.  The unit test seems to always give a bootstrap support of 100% which is sort of suspicious, but I don't know if I will thoroughly investigate it.  Let me know how it works for you.

**Comment by lskatz** [comment]
Another fix in v0.55.  Should be better now.

**Comment by kloetzl** [comment]
Skimming through the code I think you correctly implemented the idea. However, I am unsure if it is actually useful; Have to think more about that and evaluate some data sets. Thanks a lot!

**Comment by lskatz** [comment]
@kloetzl any feedback?  Should I close the issue?

**Comment by kloetzl** [comment]
In the coming weeks I will not have the time to look into this further. Thanks for your effort so far!
