### ISSUE TITLE
mashtree_jackknife.pl exited

### ISSUE THREAD

**Issue by Caro-Ca** [lskatz/mashtree#42]
Hi! 
I am planning to use `mashtree_bootstrap.pl --reps 100 --numcpus 12 *.msh -- --min-depth 0 > mashtree.bootstrap.dnd ` but on anaconda there is no mashtree_bootstrap.pl and by git cloning I got this: 
```
t/06_jackknifingHashes.t .. 1/5 Bailout called.  Further testing stopped:  mashtree_jackknife.pl exited with an error code 0
# Can't locate List/MoreUtils.pm in @INC (you may need to install the List::MoreUtils module) (@INC contains: /home/edgar/Mash/                         mashtree/blib/lib /home/edgar/Mash/mashtree/blib/arch /home/edgar/perl5/lib/perl5/x86_64-linux-thread-multi /home/edgar/perl5/l                         ib/perl5/x86_64-linux-thread-multi /home/edgar/perl5/lib/perl5 /home/edgar/perl5/lib/perl5/x86_64-linux-thread-multi /home/edga                         r/perl5/lib/perl5 /home/edgar/perl5/lib/perl5/x86_64-linux-thread-multi /home/edgar/perl5/lib/perl5 /home/edgar/anaconda2/lib/p                         erl5/site_perl/5.22.0/x86_64-linux-thread-multi /home/edgar/anaconda2/lib/perl5/site_perl/5.22.0 /home/edgar/anaconda2/lib/perl                         5/5.22.0/x86_64-linux-thread-multi /home/edgar/anaconda2/lib/perl5/5.22.0 .) at ./bin/mashtree_jackknife.pl line 14.
# BEGIN failed--compilation aborted at ./bin/mashtree_jackknife.pl line 14.
FAILED--Further testing stopped: mashtree_jackknife.pl exited with an error code 0
Makefile:925: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 255

```

This is when I installed mashtree by using: conda install -c bioconda mashtree, but I got this warning: 

```
(base) edgar@pathos:~/anaconda2/bin$ mashtree.pl --help
mashtree.pl: Mashtree::logmsg: WARNING: the executable mashtree.pl is deprecated. Please switch to the mashtree executable (without the .pl).
```
Thank you for your help.

**Comment by lskatz** [comment]
Hi @Caro-Ca !  It's possible that the Conda versions are out of date, given those errors.  The second error shows that `mashtree.pl` instead of `mashtree` is in your path.  The first error shows that the perl module dependencies were not installed (`List::MoreUtils` and possibly others).

Do you want to try to install it via cpan?  https://github.com/lskatz/mashtree/blob/master/README.md#installation-from-cpan

**Comment by lskatz** [comment]
I might be slightly wrong because it looks like the site here has the latest version number.  But I don't think that my earlier advice is wrong.  https://anaconda.org/bioconda/mashtree

**Comment by Caro-Ca** [comment]
Hi!
Instead of using mash conda, I am using mashtree from your repository. I tried to download it by using CPAN. After I used `cpanm -L ~ Mashtree`, I found an error saying that I need to install `graph-dijkstra`. For that I used `https://github.com/LincolnTechOpenSource/graph-dijkstra`. However, npm was not installed. For that I used `https://github.com/npm/cli`, but it downloads me cli. I used this link because the other websites were not friendly explaining how to download npm., but I guess it is not the right website to download npm. 

Could you help me find an easy way to install mashtree? 
On the other hand, when I type `~/Mash/mashtree/bin$ ./mashtree_bootstrap.pl help `, I get this: 
```
mashtree_bootstrap.pl: main: Temporary directory will be /tmp/MASHTREE_BOOTSTRAP.YxiloR
mashtree_bootstrap.pl: main: WARNING: You have very few reps planned on this mashtree run. Recommended reps are at least 100.
mashtree_bootstrap.pl: main: Running mashtree on full data (0 targets)
mashtree: main: Temporary directory will be /tmp/MASHTREE_BOOTSTRAP.YxiloR/observed
mashtree: main: mashtree on 1 files
mashtree: main::main: ERROR: I could not find reads path at help 
Stopped at /home/edgar/Mash/mashtree/bin/mashtree line 93.
mashtree_bootstrap.pl: main::main: Died 
Stopped at ./mashtree_bootstrap.pl line 104.
```
Thank you in advance.

**Comment by Caro-Ca** [comment]
And this is by typing `~/Mash/mashtree/bin$ mashtree help`:
```
mashtree: main::main: mashtree: use distances from Mash (min-hash algorithm) to make a NJ tree
  Usage: mashtree [options] *.fastq *.fasta *.gbk *.msh > tree.dnd
  NOTE: fastq files are read as raw reads;
        fasta, gbk, and embl files are read as assemblies;
        Input files can be gzipped.
  --tempdir            ''   If specified, this directory will not be
                            removed at the end of the script and can
                            be used to cache results for future
                            analyses.
                            If not specified, a dir will be made for you
                            and then deleted at the end of this script.
  --numcpus            1    This script uses Perl threads.
  --outmatrix          ''   If specified, will write a distance matrix
                            in tab-delimited format
  --version                 Display the version and exit

  TREE OPTIONS
  --truncLength        250  How many characters to keep in a filename
  --sort-order         ABC  For neighbor-joining, the sort order can
                            make a difference. Options include:
                            ABC (alphabetical), random, input-order

  MASH SKETCH OPTIONS
  --genomesize         5000000
  --mindepth           5    If mindepth is zero, then it will be
                            chosen in a smart but slower method,
                            to discard lower-abundance kmers.
  --kmerlength         21
  --sketch-size        10000
   
Stopped at /home/edgar/anaconda2/bin/mashtree line 65.
```

**Comment by lskatz** [comment]
Interesting, looks like you are still running it from anaconda but it works. The module that wasn't installing is a perl module, not a node one, but it doesn't seem to matter because the usage popped up. That particular module is rarely used anyway. Don't worry about it because it will complain if it's needed and isn't found.

However if you want to make sure it's all complete, you can run the cpanm command with --force.

Let me know how it goes when you run it on your data!

**Comment by Caro-Ca** [comment]
Thank you for your help! It ran perfectly. I could get the distances but how can I build a branching diagram now??

**Comment by lskatz** [comment]
Ok great!! The easiest way is to use -o file.dnd

Report back!

**Comment by Caro-Ca** [comment]
I could run `~/Mash/mashtree/bin$ mashtree_bootstrap.pl --reps 100 --numcpus 12 *.msh -- --min-depth 0 > mashtree.bootstrap.dnd ` but now I cannot see the parameters for mashtree_bootstrap nor for mashtree. 
```
edgar@pathos:~/Mash/mashtree/bin$ mashtree help
mashtree: main: Temporary directory will be /tmp/MASHTREE.zX9j8E
mashtree: main: mashtree on 1 files
mashtree: main::main: ERROR: I could not find reads path at help 
Stopped at /home/edgar/bin/mashtree line 89.
```
```
edgar@pathos:~$ mashtree_bootstrap.pl help
Can't locate List/MoreUtils.pm in @INC (you may need to install the List::MoreUtils module) (@INC contains: /home/edgar/perl5/lib/perl5/x86_64-linux-thread-multi /home/edgar/perl5/lib/perl5 /home/edgar/anaconda2/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi /home/edgar/anaconda2/lib/perl5/site_perl/5.22.0 /home/edgar/anaconda2/lib/perl5/5.22.0/x86_64-linux-thread-multi /home/edgar/anaconda2/lib/perl5/5.22.0 .) at /home/edgar/bin/mashtree_bootstrap.pl line 14.
BEGIN failed--compilation aborted at /home/edgar/bin/mashtree_bootstrap.pl line 14.
```
Could you tell me how to use -o file.dnd?

**Comment by lskatz** [comment]
`-o file.dnd` is just an alternative to what you are doing, and so that is fine.  You won't need it.

The first warning `I could not find reads path at help` indicates that it thinks you were providing a reads file named `help`.  You can run `mashtree --help` for more usage.

The second warning indicates that it cannot find the perl module `List::MoreUtils`.  You can install it by running `cpanm -l . --installdeps .`  If that works, then I will add it to the documentation.

**Comment by Caro-Ca** [comment]
This is what I got:
```
:~$ cpanm -l --installdeps
Usage: cpanm [options] Module [...]

Try `cpanm --help` or `man cpanm` for more options.
```

**Comment by lskatz** [comment]
Missing the dots

**Comment by Caro-Ca** [comment]
This is what I got: 
```
(base) edgar@pathos:~/Mash/mashtree/bin$ cpanm -l . --installdeps .
--> Working on .
Configuring /home/edgar/Mash/mashtree/bin ... N/A
! Configuring . failed. See /home/edgar/.cpanm/work/1569227730.41476/build.log for details.
(base) edgar@pathos:~/Mash/mashtree/bin$ cd
(base) edgar@pathos:~$ cpanm -l . --installdeps .
--> Working on .
Configuring /home/edgar ... N/A
! Configuring . failed. See /home/edgar/.cpanm/work/1569227739.41484/build.log for details.
(base) edgar@pathos:~$

```

**Comment by Caro-Ca** [comment]
This is the  `/home/edgar/.cpanm/work/1569227730.41476/build.log`
```
cpanm (App::cpanminus) 1.7043 on perl 5.022001 built for x86_64-linux-gnu-thread-multi
Work directory is /home/edgar/.cpanm/work/1569227730.41476
You have make /usr/bin/make
You have LWP 6.15
You have /bin/tar: tar (GNU tar) 1.28
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
You have /usr/bin/unzip
--> Working on .
Entering /home/edgar/Mash/mashtree/bin
Configuring /home/edgar/Mash/mashtree/bin
-> N/A
! Configuring . failed. See /home/edgar/.cpanm/work/1569227730.41476/build.log for details.

```

**Comment by lskatz** [comment]
cd into the base directory, then run that command.  And for good measure, add onto your `PERL5LIB`.  E.g.,

```
cd /home/edgar/Mash/Mashtree
cpanm -l . --installdeps .
export PERL5LIB=$PERL5LIB:/home/edgar/Mash/Mashtree/lib/perl5
```

**Comment by Caro-Ca** [comment]
Perfect! This is what I got
```
Successfully installed Array-Heap-ModifiablePriorityQueue-1.10
Building and testing Graph-Dijkstra-0.70 ... FAIL
! Installing Graph::Dijkstra failed. See /home/edgar/.cpanm/work/1569242872.46810/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'Graph::Dijkstra' is not installed
! Bailing out the installation for Mashtree-0.57.
5 distributions installed
```

**Comment by lskatz** [comment]
Hmmm let's add a force in that
```
cd /home/edgar/Mash/Mashtree
cpanm -l . --installdeps . --force
export PERL5LIB=$PERL5LIB:/home/edgar/Mash/Mashtree/lib/perl5
```

**Comment by Caro-Ca** [comment]
This is what I could get by running `~/Mash/mashtree/bin$ mashtree_bootstrap.pl --reps 100 --numcpus 12 *.msh -- --min-depth 0 > mashtree.bootstrap.dnd `:
`(R25_CRRNanoF.improved3:0.00546,((R28_CRRNanoF.improved3:0.00226,R27_CRRNanoF.improved3:0.00183)100:0.00272,R10_CRRNanoF.improved3:0.00516)100:0.00062,(Xylaria_flabelliformis:0.27582,(Rn400_CRRNanoF.improved3:0.00397,R19_CRRNanoF.improved3:0.00389)100:0.01624)100:0.01462)100;`
and how can I make a branched diagram like this: 
[(![image](https://user-images.githubusercontent.com/51200315/65439909-39207f80-de28-11e9-8dbb-41517bace821.png))]

Thank you so much for help.

**Comment by lskatz** [comment]
I'm so glad it worked! Closing the issue.

**Comment by Caro-Ca** [comment]
Hi!
Maybe I didn't make myself clear. I already have the distances among my strains, but now I want to create a tree graphic like the one it is in the last message. I am reading different manuals, and the Mash paper doesn't tell anything about how to show the graphical version of the distances. I just need this final method. 
Thank you in advance for your help!

**Comment by lskatz** [comment]
I think for visualization, it gets outside of the Mashtree scope.  However, I have some advice on a different GitHub site: https://github.com/lskatz/lyve-SET/blob/master/docs/VIZ.md#tree

For your other comment: The third column is distance (lower is closer), fourth is p-value (lower is better), and fifth is shared hashes (higher is closer).  Your example shows two genomes not very close.  If the last value were higher (more hashes), then your third column would be lower (less distance).
