### ISSUE TITLE
mash sketch ERROR: Unrecognized option: -S

### ISSUE THREAD

**Issue by JPegorino** [lskatz/mashtree#45]
I'm running mashtree 0.57 (anaconda version) on SRA sequences assembled into contigs/scaffolds and I'm getting the following error:
```
mashtree: main: Temporary directory will be /local/136489.1.eddie/MASHTREE.7_2A9p
mashtree: main: mashtree on 2339 files
mashtree: mashSketch(TID1): This thread will work on 2339 sketches
mashtree: mashSketch(TID1): Working on file 1 out of 2339
mashtree: mashSketch(TID1): ERROR running mash sketch -S 42 -k 19 -s 10000   -o /local/136489.1.eddie/MASHTREE.7_2A9p/ERR2632350_ctg2.fasta ootw/ERR2632350_ctg2.fasta 2>&1!
  ERROR: Unrecognized option: -S

Thread 1 terminated abnormally: mashtree: main::mashSketch: Died
Stopped at /exports/cmvm/eddie/eb/groups/fitzgerald_grp/software/conda_envs/jamieG/envs/tree/bin/mashtree line 298.
mashtree: mashDistance: Waiting to join thread (1/1, TID2)
mashtree: mashDistance: Databasing distances (1/1, TID2)
mashtree: mashDistance: Converting to phylip format into /local/136489.1.eddie/MASHTREE.7_2A9p/distances.phylip
mashtree: Mashtree::createTreeFromPhylip: Can't call method "as_text" on an undefined value
Stopped at /exports/cmvm/eddie/eb/groups/fitzgerald_grp/software/conda_envs/jamieG/envs/tree/lib/site_perl/5.26.2/Mashtree.pm line 217.
```
I'm not sure what the error means or where I might be going wrong?
I'm using 2 8G cores of a high compute cluster (sge) and I ran mashtree with the command: `mashtree --numcpus 2 --kmerlength 19 --outtree ./mashtree.dnd ootw/*` where all the files in ootw are .fasta genome assemblies.

Any suggestions would be greatly appreciated!

**Comment by lskatz** [comment]
It means you are using Mash v1 but you need Mash v2.  I made a better error message in development.  Please see #44 for slightly more info.  Happy mashing!

**Comment by colindaven** [comment]
This is still happening with the bioconda mashtree in Sept 2021 (at least for me in this env).

**Comment by lskatz** [comment]
Could you send your version of mash and mashtree? And your log?

**Comment by colindaven** [comment]
Ah, sorry, I wasn't complaining, just noting for posterity that the bioconda recipe wasn't working for me. I successfully used the docker container https://hub.docker.com/r/staphb/mashtree mentioned in your install log to create a singularity container.
That worked like a charm, thanks!
