### ISSUE TITLE
INSTALL.md Quicktree unzipping cmd error

### ISSUE THREAD

**Issue by mihkelvaher** [lskatz/mashtree#46]
Quicktree instructions:
```
...
$ wget https://github.com/khowe/quicktree/archive/v2.5.zip
$ tar xvf v2.5.tar.gz 
...
```
There are different files mentioned (zip is correct).

Also, it would be easier to copy-paste commands without the leading dollar sign.

**Comment by lskatz** [comment]
Thanks for the feedback!  Fixed in 49131c2.
