### ISSUE TITLE
Error: I could not understand what kind of file this is

### ISSUE THREAD

**Issue by samlipworth** [lskatz/mashtree#48]
when a file ends *fa.fasta eg. ec121fe6-979b-42fd-965d-551cb5d881fa.fasta mashtree throws an error. The file is just a normal fasta file.

**Comment by samlipworth** [comment]
happens for all such files I have tried

**Comment by lskatz** [comment]
Thanks for sharing! Could you post the full command and log? I am sure it is an issue with the suffix but it would help me track down where to fix it faster.
