### ISSUE TITLE
--numcpus doesn't seem to work with mashtree_jackknife.pl

### ISSUE THREAD

**Issue by mcroxen** [lskatz/mashtree#51]
I tried making a tree with mashtree_jackknife.pl using --numcpus 4 and the resulting tree only had 3/48 genomes included.

Not using --numcpus generated a tree with all 48 genomes included.

**Comment by lskatz** [comment]
I couldn't replicate the problem.  Could you provide more steps on how to reproduce it?  This is what I did:

    # Use the test data in the installation directory
    cd mashtree/t/data
    # Create a total of 24 samples
    for i in `seq 1 20`; do cp sample1.fastq.gz sample1_${i}.fastq.gz -v ;done;
    # jack knifing with 100 reps and 24 samples 
    mashtree_jackknife.pl --numcpus 4 *.fastq.gz --reps 100

    (sample1_8:0.00000,sample1_9:0.00000,(((((((((((((((((((((sample4:0.00206,sample3:0.00197)52:0.00005,sample2:0.00204)100:0.00210,sample1:0.00000)2:0.00000,sample1_1:0.00000)2:0.00000,sample1_10:0.00000)0:0.00000,sample1_11:0.00000)0:0.00000,sample1_12:0.00000)0:0.00000,sample1_13:0.00000)0:0.00000,sample1_14:0.00000)0:0.00000,sample1_15:0.00000)0:0.00000,sample1_16:0.00000)0:0.00000,sample1_17:0.00000)0:0.00000,sample1_18:0.00000)0:0.00000,sample1_19:0.00000)0:0.00000,sample1_2:0.00000)0:0.00000,sample1_20:0.00000)0:0.00000,sample1_3:0.00000)0:0.00000,sample1_4:0.00000)0:0.00000,sample1_5:0.00000)0:0.00000,sample1_6:0.00000)0:0.00000,sample1_7:0.00000)1:0.00000)100;
    # => 24 leaves on the tree

**Comment by mcroxen** [comment]
Here is my code:

`mashtree_jackknife.pl --reps 100 --numcpus 4 --outmatrix matrix.txt -- --file-of-files list.lst --genomesize 25000000 --mindepth 0 > tree.dnd`

Perhaps it has to do with my setup? WSL through Windows 10

**Comment by mcroxen** [comment]
I should add, I think you need to use --mindepth 0 to make this happen

**Comment by lskatz** [comment]
I can confirm the bug, and it happens with `--file-of-files`.  I'll keep looking into it.

**Comment by lskatz** [comment]
I fixed the bug in v1.1 (733f0b6) but I think it still exists in the boostrapping mode and so I will leave the ticket open.

**Comment by lskatz** [comment]
Fixed in v1.1.2

**Comment by lskatz** [comment]
Also added v1.1.2 to cpan so that it can be installed via the `cpanm` instructions.
