### ISSUE TITLE
Allow use of premade sketches in conjunction with --file-of-files 

### ISSUE THREAD

**Issue by bede** [lskatz/mashtree#52]
Mashtree v1.1.2 appears to assume that a supplied FOFN contains fastqs, and unlike the command line args, is not accepting of .msh sketches. It would be useful to be able to supply sketches inside a FOFN when dealing with large datasets approaching `ARG_MAX` when input with shell globbing.

**Comment by CBorreda** [comment]
Hi Bade,

I was interested in using a file of files with .msh files and it worked fine for mashtree 1.1.2. I recently installed it using the cpanm method described in INSTALL.md 

I'm just a user but wanted to share with you that it is working for me.

Best

**Comment by bede** [comment]
Thanks @CBorreda : )
