### ISSUE TITLE
Mashtree::createTreeFromPhylip: Can't call method "as_text" on an undefined value 

### ISSUE THREAD

**Issue by karel-brinda** [lskatz/mashtree#54]
**Describe the bug**
I'm trying to compute a tree from precomputed sketches ([sketches.tar.gz](https://github.com/lskatz/mashtree/files/5289238/sketches.tar.gz)). I always get the following error (see also the full [log.txt](https://github.com/lskatz/mashtree/files/5289237/log.txt)):
```
mashtree: mashDistance: Databasing distances (5/8, TID13)
mashtree: mashDistance: Waiting to join thread (6/8, TID14)
mashtree: mashDistance: Databasing distances (6/8, TID14)
mashtree: mashDistance: Waiting to join thread (7/8, TID15)
mashtree: mashDistance: Databasing distances (7/8, TID15)
mashtree: mashDistance: Waiting to join thread (8/8, TID16)
mashtree: mashDistance: Databasing distances (8/8, TID16)
mashtree: mashDistance: Converting to phylip format into /var/folders/5c/b4402v855qd5lf_dr0cj93gh0000gn/T/MASHTREE.YtCWcT/distances.phylip
mashtree: Mashtree::createTreeFromPhylip: Can't call method "as_text" on an undefined value 
Stopped at /Users/karel/miniconda/envs/mashtree/lib/site_perl/5.26.2/Mashtree.pm line 217.
```

**Desktop (please complete the following information):**
 - OS: iOS
 - Version Mashtree 1.0.4 (tested also with 1.2.0)
 - which method did you install with? conda

**Comment by lskatz** [comment]
This was a tough one but I think I have a potential reason, that they all seem to be named the same thing.  They seem to be colliding with each other in the sqlite database.

```bash
[gzu2@monolith1 mashtree-help]$ \ls sketches/*.msh | xargs -n 1 mash info | grep '\.fa' | sort | uniq -c
     46   /well/iqbal/people/phelim/mash/tmp/1696.fa
     99   /well/iqbal/people/phelim/mash/tmp/1697.fa
    100   /well/iqbal/people/phelim/mash/tmp/1698.fa
    100   /well/iqbal/people/phelim/mash/tmp/1699.fa
     53   /well/iqbal/people/phelim/mash/tmp/1700.fa
```

**Comment by karel-brinda** [comment]
Great, thank you so much for figuring out what's going wrong! I thought Mashtree was using the actual files and had no idea that the original names are stored in the `.msh` files.
