### ISSUE TITLE
Conda Install not working

### ISSUE THREAD

**Issue by JChristopherEllis** [lskatz/mashtree#57]
After installing both mash and mashtree with the conda install option it can not find the mashtree command. Has anyone else experienced this problem?

**Comment by lskatz** [comment]
Hi, I apologize but I do not have control over the conda installation.  Please do use the native perl installer if conda does not work for you.  I feel awkward about mixing the perl and python streams but am glad that someone else out there is maintaining the conda environment.

**Comment by cmkobel** [comment]
Hi
Who is maintaining the conda package?
I'm having trouble installing mashtree currently. It used to work quite well, but now I'm getting this problem on a fresh installation of miniconda3 on two independent systems:
```
user@host ~ $ conda install -c bioconda mashtree
[...]
Encountered problems while solving:
  - nothing provides perl 5.22.0* needed by mashtree-0.12-pl5.22.0_0
```
