### ISSUE TITLE
Support for .gz files (genbank and fasta)

### ISSUE THREAD

**Issue by tseemann** [lskatz/mashtree#6]
Not sure this is easy, because you depend on Bioperl to examine the file extension to determine the type?

**Comment by lskatz** [comment]
There is now an extra step in there to uncompress gz, bz2, and zip files.  Added in b26f249a02965644ecf0cf0cf3cc5af1af9073d0

**Comment by tseemann** [comment]
One of the tricks I use it `gzip -c -d -f` .

The `-f` will behave as `cat` if the file is not gzipped, so you don't need extra code.
