### ISSUE TITLE
Postgres Migration Error(ORA2PG) FATAL: 12557 ... ORA-12557: TNS:protocol adapter not loadable (DBD ERROR: OCIServerAttach)

### ISSUE THREAD

**Issue by jitenpansara** [lskatz/mashtree#60]
Hello All,

I am trying to migrate my Oracle database to Postgres. I am getting below error while running ora2pg. Need your quick help please. I tried to connect using below command and i am able to connect. Even while configuration, i realized that i face 'GPLv3' License issue, will it make any impact?
![connection string](https://user-images.githubusercontent.com/53655001/114686667-a3fa1a00-9d30-11eb-80d2-8cdff43cdbaf.JPG)
![license issue](https://user-images.githubusercontent.com/53655001/114686677-a78da100-9d30-11eb-95cd-e0cc13d65880.JPG)
![ora2pg error](https://user-images.githubusercontent.com/53655001/114686686-a8bece00-9d30-11eb-8a4a-61677cecfefa.JPG)

sqlplus system/***********@localhost:1521/ORCL1

Error while executing ora2pg.
FATAL: 12557 ... ORA-12557: TNS:protocol adapter not loadable (DBD ERROR: OCIServerAttach)

Screenshots attached. Kindly go through it and let me know if you have any inputs for the same.

**Comment by jitenpansara** [comment]
![config settings](https://user-images.githubusercontent.com/53655001/114687957-df491880-9d31-11eb-8fa0-037914fff645.JPG)
I already have required connection details in my ora2pg_dist.conf file.

**Comment by jitenpansara** [comment]
I already have required connection details in my ora2pg_dist.conf file. Kindly go through it.
![Uploading config settings.JPG…]()

**Comment by jitenpansara** [comment]
I already have required connection details in my ora2pg_dist.conf file. Kindly go through it.
![config settings](https://user-images.githubusercontent.com/53655001/114693171-f50d0c80-9d36-11eb-9cce-accece9e353c.JPG)

**Comment by lskatz** [comment]
I don't think that this was meant for the mashtree project
