### ISSUE TITLE
Unknown option: kmerlength

### ISSUE THREAD

**Issue by Lamm-a** [lskatz/mashtree#63]
`--kmerlength` is being flagged as unknown but the help page says it exists. Any idea how I can solve this a I want to run a series of kmers.

**Comment by lskatz** [comment]
Which version are you using? What error do you get? The option seems to be active https://github.com/lskatz/mashtree/blob/adac2ead7f4ab27ba8e11a82a7626136c6ebeed9/bin/mashtree#L41

**Comment by Lamm-a** [comment]
Apologies I forgot to leave my version:
`Mashtree 1.2.0`

*Error:*
```
mashtree_bootstrap.pl --reps 100 --numcpus 16 --outmatrix $dismat $path/*.$extension --kmerlength $kmer > $outfile

Unknown option: kmerlength
mashtree_bootstrap.pl: main::main: Died
Stopped at /home/projects/ku_00014/people/robmur/programmes/miniconda3/envs/mashtree/bin/mashtree_bootstrap.pl line 43.
```

**Comment by lskatz** [comment]
Some options line that one for the bootstrap or jack knife scripts, you have to have after the double dash. For example the one shown in this section https://github.com/lskatz/mashtree#adding-confidence-values

Also see the usage with mashtree_boostrap.pl --help or in the source code, https://github.com/lskatz/mashtree/blob/ffb068af5933b01b1df0c74b27d3c15e2096e529/bin/mashtree_bootstrap.pl#L243
