### ISSUE TITLE
mashtree: Argument list too long

### ISSUE THREAD

**Issue by noorshu** [lskatz/mashtree#67]
I am trying to run mashtree on around 50,000 genomes, but I am getting an error stating that the argument list is too long. I then tried creating a fastas.fofn file with all the fastas to use the --file-of-files argument, but I get the following error instead:

mashtree: main: Temporary directory will be /tmp/MASHTREE.Z3oBxm
mashtree: main: mashtree on 4 files
mashtree: main::main: ERROR: I could not find reads path at --file-of-files 
Stopped at /mnt/nas2/virtual_environments/mashtree/bin/mashtree line 88.

This is the command I am running in the slurm script:
mashtree -- --file-of-files /mnt/fastas.fofn > /mnt/mashtree_output.dnd --numcpus 10

Can you please help me with the error?
I'm not sure how else to run mashtree on a large number of genomes. Is there a limit on the number of genomes it can run on?

Thanks!

**Comment by lskatz** [comment]
It looks like you have `--` before `--file-of-files` and so it assumes everything after the `--` is a genomic filename.

**Comment by noorshu** [comment]
Thanks for the quick reply! I tried that and got this error below:

Unknown option: file-of-files
mashtree: main::main: Died 
Stopped at /mnt/nas2/virtual_environments/mashtree/bin/mashtree line 39.

**Comment by noorshu** [comment]
Thanks! That worked along with updating to the latest version of mashtree.
