### ISSUE TITLE
Update help output and docs for .GBK support

### ISSUE THREAD

**Issue by tseemann** [lskatz/mashtree#7]
eg 
 Usage: mashtree_wrapper.pl [options] [-- mashtree.pl options] *.fastq.gz *.fasta > tree.dnd

add *.gbk

**Comment by lskatz** [comment]
Added in d093fbd2615d82d756738eebdc6187d738bfaafa and b26f249a02965644ecf0cf0cf3cc5af1af9073d0

**Comment by lskatz** [comment]
And reflected in a new release v0.11
