### ISSUE TITLE
Mashtree not running 

### ISSUE THREAD

**Issue by parolinaline** [lskatz/mashtree#72]
**Describe the bug**
I am trying to run mashtree with a small number of fasta files as a test and it is not working, it looks like it is not running at all. It does give an output, but it is empty. 
I am using this command inside the folder with the fasta files
$ mashtree ./*.fasta > tree.dnd

I press enter and nothing happens, check the screenshot below:

**Screenshots**
![image](https://user-images.githubusercontent.com/91032260/214694646-abbb68ff-20e5-416f-b2d0-a153852c1eb8.png)

**Desktop (please complete the following information):**
 - I am using the NESI supercomputer that has the mashtree already installed and all other necessary softwares
 - Version: Mashtree 1.2.0
 - which method did you install with?  NESI already has it installed (I don`t know how they did it)

**Comment by parolinaline** [comment]
> **Describe the bug** I am trying to run mashtree with a small number of fasta files as a test and it is not working, it looks like it is not running at all. It does give an output, but it is empty. I am using this command inside the folder with the fasta files $ mashtree ./*.fasta > tree.dnd
> 
> I press enter and nothing happens, check the screenshot below:
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/91032260/214694646-abbb68ff-20e5-416f-b2d0-a153852c1eb8.png)
> 
> **Desktop (please complete the following information):**
> 
> * I am using the NESI supercomputer that has the mashtree already installed and all other necessary softwares
> * Version: Mashtree 1.2.0
> * which method did you install with?  NESI already has it installed (I don`t know how they did it)

**Comment by lskatz** [comment]
I am clueless and so I guess I will apply "help wanted" to this ticket.  You can run mashtree to get usage but as soon as you do _anything_ in it, it freezes without even a message to stdout.

**Comment by lskatz** [comment]
My best guess is that something like `mash` is on a drive that is freezing.

**Comment by rpetit3** [comment]
How was mashtree installed on NESI?
