### ISSUE TITLE
Remove `Thread::Queue` in favor of arrays

### ISSUE THREAD

**Issue by lskatz** [lskatz/mashtree#8]
There is a potential speed up if I just send an equal number of files to each thread instead of a Queue.  `Thread::Queue` locks up each thread momentarily each time there is a `dequeue` statement.  However, this lock would not occur if I just send an array of files to each thread.  Randomizing the array would help distribute the load to each thread but there could be a smarter way to do it.

There is a queue for both `mash sketch` and `mash dist`.

**Comment by tseemann** [comment]
What do you mean locks up momentarily?  Is this a big problem? A queue is the right thing to do. Sharing evenly will work, but might not be optimal.

**Comment by lskatz** [comment]
I don't think it's a big problem but it's something I've wanted to try out.  Every `dequeue` call locks up all the other threads momentarily and so it is a possible slow step (same thing if I had multiple `enqueue`).  As long as the queue isn't being added onto, static arrays might be faster.  The downside is if it is not balanced well, e.g., if one thread gets all the assemblies and another thread gets all the raw reads.

So I think I want to try this out but it might not be in the master branch and might not make it into a version.

**Comment by lskatz** [comment]
Doesn't seem to be a huge speed difference yet but I want to try it a few different ways.  I put it into a different branch, starting with f25a649

**Comment by lskatz** [comment]
There are slight time differences and I merged this branch in 6f7b2dd.  If it ever turns out to be weird, I can change it back.
