### ISSUE TITLE
Illumina Short Reads

### ISSUE THREAD

**Issue by rmormando** [lskatz/mashtree#80]
If I have Illumina short-read sequences that separate a sample by `sample_1.fastq.gz` and `sample_2.fastq.gz` should I combine the files to make it one `sample.fastq.gz` or is it okay to leave them in the folder among other samples and their two files?

```
sample1_1.fastq.gz
sample1_2.fastq.gz
sample2_1.fastq.gz
sample2_2.fastq.gz
sample3_1.fastq.gz
sample3_2.fastq.gz
...
```

**Comment by lskatz** [comment]
Hi, this is similar to #65 . It is my belief that running Mashtree on R1 alone should be sufficient in most cases. However, I am open to anyone helping to provide evidence for one method vs another.
