### ISSUE TITLE
Request for new release with ROSS bug fix?

### ISSUE THREAD

**Issue by verdurin** [lskatz/mashtree#82]
Hello

I've been working on packaging Mashtree for [EasyBuild](https://easybuild.io) and the reviewer pointed out that you've added a fix for download problems with ROSS but haven't included that in a formal release yet. 
Were you thinking of making a release soon including this fix?

**Comment by lskatz** [comment]
Here you go!

https://github.com/lskatz/ROSS/releases/tag/v0.3.1

It is also deprecated and so I will look into whether I can just update to Fasten

**Comment by lskatz** [comment]
Removed ROSS in #83

**Comment by verdurin** [comment]
@lskatz thanks for the quick response. What I meant was a new release of `Mashtree` rather than `ROSS`...

**Comment by verdurin** [comment]
Sorry, I was focusing on the CPAN version, but the build works fine with the GitHub release. 
Thanks.

**Comment by lskatz** [comment]
Hi, is this sufficient for v1.4.0 or do you need the very latest? https://metacpan.org/pod/Mashtree
![image](https://github.com/lskatz/mashtree/assets/14798/4c1f0611-996c-4719-996c-eff5ac8de237)

**Comment by lskatz** [comment]
I uploaded a new mashtree version to cpan

**Comment by verdurin** [comment]
Yes, that's great - thanks.
