### ISSUE TITLE
Ways to add NCBI assembly in mash tree

### ISSUE THREAD

**Issue by kusandeep** [lskatz/mashtree#85]
Hi @lskatz , Is there a way to add certain genera or species assembly in the mash tree to compare the in-house isolated species genome? Currently, I am downloading the assembly of interested genera and running the mash tree on them.. Thanks for the help.

**Comment by lskatz** [comment]
Yes, if you want to add an assembly, you can give it as a parameter as a fasta or gbk file.  Please see the usage <https://github.com/lskatz/mashtree?tab=readme-ov-file#two-modes-fast-or-accurate>.

**Comment by kusandeep** [comment]
Thanks.
