### ISSUE TITLE
use bindash 2.0 instead of mash (100 times faster)

### ISSUE THREAD

**Issue by jianshu93** [lskatz/mashtree#87]
Dear Mashtree team,

We recently updated BinDash to bindash 2 (here: https://github.com/zhaoxiaofei/bindash or here: https://www.biorxiv.org/content/10.1101/2024.03.13.584875v1.abstract), use one permutation Minhash with optimal/faster/re-randomized densification, which is about 1000 times faster than Mash for millions of genomes. The accuracy is exactly the same with Mash, both theoretically and in practice, thanks to the theroretical breakthrough of one permutation Minhash with optimal densification (http://proceedings.mlr.press/v70/shrivastava17a.html). Would it be possible to use BinDash2 instead of Mash for next version. I image this will allow mashtree to scale to millions of genomes.

Thanks,

Jianshu

**Comment by lskatz** [comment]
Hi! I am finally starting to think about how to do that and I am transferring those ideas over to [this generalized pipeline](https://github.com/lskatz/dists2trees/). I think it could be easier to try to dream up instructions on how to use BinDash with dists2trees. Let me know if you want to submit specific ideas in the issues tab? <https://github.com/lskatz/dists2trees/issues>

We could think of specific instructions in the documentation or maybe a specific wrapper script.

**Comment by jianshu93** [comment]
Yeah I agree, bindash 2 output format is exactly the same with Mash, so the Mash equation transformed Jaccard similarity is the output (a distance).  Additionally I think we can also update it to metagenomes (build for metagenome comparisons), in which we have much lager number of kmers to hash and Minhash is not so memory efficient, I am thinking using HyperMinHash (https://github.com/lukaslueg/hyperminhash, original paper here: https://ieeexplore.ieee.org/abstract/document/9039684), I am working on it now and will have binary soon (also in Rust), then we combine both Minhash with neighbor-joining tree? Seems to be a paper to me. 

thanks,

Jianshu
