### ISSUE TITLE
Add --version option

### ISSUE THREAD

**Issue by tseemann** [lskatz/mashtree#9]
```
% mashtree.pl --version
mashtree 1.12
```

**Comment by lskatz** [comment]
Added in f43558ad2e865080eecb741e81265f65a4ad8415

**Comment by lskatz** [comment]
Now in version 0.14

**Comment by tseemann** [comment]
Can you get rid of the word `version` in the middle? 
For automatic parsing purposes.

**Comment by lskatz** [comment]
Fixed in b854544 v0.16
